apiVersion: v1
kind: Secret
metadata:
  name: appname-secrets

stringData:
  SHIU: "secret"

# also valid
# data:
#   SHIU: "c2VjcmV0Cg=="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname

spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname

  template:
    metadata:
      labels:
        app: appname

    spec:
      containers:
        - name: nginx-container
          image: nginx
          # use secretKeyRef instead
          env:
            - name: SHIU
              valueFrom:
                secretKeyRef:
                  name: appname-secrets
                  key: SHIU
