apiVersion: batch/v1
kind: CronJob
metadata:
  name: appname-cron
spec:
  schedule: "* * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: echo
              image: busybox
              command: ["echo", "job is done in cronjob"]
