apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname

spec:
  replicas: 2
  selector:
    matchLabels:
      app: appname

  template:
    metadata:
      labels:
        app: appname

    spec:
      containers:
        - name: nginx-container
          image: nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
