[project]
name = "pedal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
    "marimo>=0.13.11",
    "pedalboard>=0.9.17",
]
